spring.application.name=backend

spring.datasource.url=jdbc:postgresql://postgres-db:5432/chatapp
#spring.datasource.url=jdbc:postgresql://postgres-db:5432/chatapp?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.jpa.properties.hibernate.format_sql=true

gemini.api.key=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
#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
